name: push_to_prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build and push client
        run: |
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp:client-beta .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/webapp:client-beta